export const environment = {
  production: false,
  JigsawTitle:'JigsawPuzzle',
  Puzzles:"Puzzles",
  AddPuzzle:"Add Puzzle",
  SearchPuzzle:"Search Puzzle",
  Register:"Register",
  Login:"Login",
  Username:"Username",
  Password:"Password",
  Welcome:"Welcome",
  Logout:"Logout",
  UsernamePlcholder:"your username",
  PassPlcholder:"your password",
  RegisterNewUser :"Register New User",
  Name:"Name",
  Edit:"Edit",
  Delete:"Delete",
  Previous:"Previous",
  Next:"Next",
  NumPieces:"Number of Pieces:",
  Stores:"Stores",
  AddStore:"Add New Store",
  PuzzleName:"Puzzle Name",
  Add:"Add",
  PuzzlePrice:"Puzzle Price",
  URL:"URL",
  StorePlcholder:"store url",
  EditPuzzle:"EditPuzzle"
};
